name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸ’¡ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'ğŸ§° Maintenance'
    labels: 
      - 'chore'
      - 'docs'
      - 'documantation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## ğŸš€ Change

  $CHANGES
no-changes-template: 'No Change! ğŸµ'
include-labels:
  - 'feature'
  - 'enhancement'
  - 'fix'
  - 'bugfix'
  - 'bug'
  - 'chore'
  - 'docs'
  - 'documentation'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch